# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='stage_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
