# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbomaster',
            name='date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
