# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160604_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbomaster',
            name='office_address',
            field=models.CharField(max_length=255),
        ),
    ]
