# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20160903_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbomaster',
            name='contact_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='setaside',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='zip_code',
            field=models.CharField(max_length=30),
        ),
    ]
