# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170112_1900'),
        ('contact', '0002_auto_20170203_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='related_users',
            field=models.ManyToManyField(related_name='related_users', to='userprofile.UserProfile'),
        ),
    ]
