# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0005_auto_20161207_0015'),
        ('accounts', '0003_auto_20160907_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sam.SamRecord'),
        ),
    ]
