# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
        ('opportunity', '0002_auto_20170215_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='pipeline_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.PipelineStage'),
        ),
    ]
