# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_dt', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('data_source', models.CharField(max_length=10)),
            ],
        ),
    ]
