# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_dt', models.DateTimeField()),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportHistoryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
