# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_importhistory_data_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportHistoryManager',
        ),
    ]
