# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170112_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sam.SamRecord'),
        ),
    ]
