# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_dt', models.DateField()),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
