# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0002_samhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SamHistory',
        ),
    ]
