# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0003_delete_samhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samrecord',
            name='company_nm',
        ),
        migrations.RemoveField(
            model_name='samrecord',
            name='is_8a',
        ),
        migrations.RemoveField(
            model_name='samrecord',
            name='is_hubzone',
        ),
        migrations.RemoveField(
            model_name='samrecord',
            name='is_sdb',
        ),
        migrations.RemoveField(
            model_name='samrecord',
            name='naics_codes',
        ),
        migrations.RemoveField(
            model_name='samrecord',
            name='registration_purpose',
        ),
        migrations.AddField(
            model_name='samrecord',
            name='activation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='address_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='address_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='business_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='business_type_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='buysiness_type_string',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='entity_structure',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='fiscal_year_end_close_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='last_update_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='legal_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='naics_code_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='naics_code_string',
            field=models.CharField(max_length=12000, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='naics_exception_counter',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='naics_exception_string',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='no_public_display_flag',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='phone_ext',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='sba_business_types_counter',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='sba_business_types_string',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='state',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='state_of_incorporation',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='samrecord',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='cage_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='duns',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='email_address',
            field=models.EmailField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='primary_naics',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
