# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import sam.models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0004_auto_20161207_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samrecord',
            name='activation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='business_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='business_type_counter',
            field=sam.models.IntegerBlankStringField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='duns',
            field=sam.models.IntegerBlankStringField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='fiscal_year_end_close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='last_update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='naics_code_counter',
            field=sam.models.IntegerBlankStringField(null=True),
        ),
        migrations.AlterField(
            model_name='samrecord',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
