# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0006_auto_20170109_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samrecord',
            name='naics',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
