# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FboMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitation_type', models.CharField(choices=[(b'presol', b'Pre-Solicitation'), (b'combine', b'Combined Synopsis/Solicitation'), (b'SS', b'Sources Sought'), (b'mod', b'Modification/Amendment/Cancel'), (b'SUR', b'Sale of Surplus Property'), (b'NOTICE', b'Special Notice'), (b'FORGOVSTD', b'Foreign Government Standard'), (b'award', b'Award Notice'), (b'JST', b'Justification and Approval'), (b'BUNDLE', b'Intent to Bundle Requirements'), (b'FAIR', b'Fair Opportunity / Limited Sources Justification')], max_length=20)),
                ('date', models.DateField(null=True)),
                ('agency', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=30)),
                ('class_code', models.CharField(max_length=10)),
                ('naics', models.CharField(max_length=10)),
                ('office_address', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=400)),
                ('solnbr', models.CharField(max_length=100)),
                ('response_date', models.DateField(null=True)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('setaside', models.CharField(max_length=100)),
                ('pop_country', models.CharField(max_length=50)),
                ('pop_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('fbomaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbo.FboMaster')),
            ],
        ),
    ]
