# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbomaster',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='fbomaster',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='fbomaster',
            name='contact_phone',
        ),
    ]
