# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0002_auto_20160603_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbomaster',
            name='response_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='solicitation_type',
            field=models.CharField(choices=[(b'presol', b'Pre-Solicitation'), (b'combine', b'Combined Synopsis/Solicitation'), (b'SS', b'Sources Sought'), (b'mod', b'Modification/Amendment/Cancel'), (b'SUR', b'Sale of Surplus Property'), (b'NOTICE', b'Special Notice'), (b'FORGOVSTD', b'Foreign Government Standard'), (b'award', b'Award Notice'), (b'JST', b'Justification and Approval'), (b'BUNDLE', b'Intent to Bundle Requirements'), (b'FAIR', b'Fair Opportunity / Limited Sources Justification')], max_length=20),
        ),
    ]
