# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('fbo', '0002_auto_20170201_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbomaster',
            name='contacts',
            field=models.ManyToManyField(to='contact.Contact'),
        ),
    ]
