# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0003_fbomaster_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='account',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='fbomaster',
        ),
        migrations.AlterModelOptions(
            name='fbomaster',
            options={'verbose_name': 'solicitation', 'verbose_name_plural': 'solicitations'},
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
