# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0004_auto_20170215_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbomaster',
            name='archive_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='award_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='award_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='award_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='line_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='ntype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fbomaster',
            name='pop_zip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='agency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='class_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='naics',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='office',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='office_address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='pop_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='pop_country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='setaside',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='solnbr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='subject',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='zip_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
