# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0005_auto_20170504_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbomaster',
            name='pop_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
