# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0011_auto_20161130_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbomaster',
            name='setaside',
            field=models.CharField(max_length=100),
        ),
    ]
