# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-21 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbo', '0012_auto_20161130_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbomaster',
            name='year',
        ),
        migrations.AlterField(
            model_name='fbomaster',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
